=begin
#ShipEngine API

#ShipEngine™ is the world's best multi-carrier shipping API, with more than 20 supported shipping carriers.  You can easily get and compare shipping rates, print labels, track your shipments, and validate addresses anywhere in the world.  ### Worldwide Major Carrier Support Access the top global carriers in minutes—instead of weeks. Simply [connect your existing carrier accounts](https://docs.shipengine.com/docs/setup-a-carrier) in the API dashboard, and then [begin creating labels](https://docs.shipengine.com/docs/use-a-specific-service).  ### Real-Time Tracking [Track packages](https://docs.shipengine.com/docs/track-a-package) across any of our 20+ supported carrier accounts and create tracking events to keep your customers up-to-date. Easily integrate real-time tracking information for shipments into your app, email, or SMS.  ### Get Rates Across Carriers Make sure you ship as cost-effectively as possible by [quickly comparing rates](https://docs.shipengine.com/docs/get-shipping-rates) using the ShipEngine Rates API. As long as you have the carrier connected to your account, you'll be able to see and compare different rates and services.  ### Global Address Validation No matter your shipping volume, failed deliveries and address change surcharges cut into your bottom line and damage perception with customers. Our address validation services ensure your packages make it to the right place the first time. [Learn how to leverage our address validation services here.](https://docs.shipengine.com/docs/address-validation)  ShipEngine supports address validation for over 180 countries, including the United States, Canada, Great Britain, Australia, Germany, France, Norway, Spain, Sweden, Israel, Italy, and more. 

OpenAPI spec version: 1.0.0
Contact: sales@shipengine.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ShipEngineApi::CarrierAccountsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CarrierAccountsApi' do
  before do
    # run before each test
    @instance = ShipEngineApi::CarrierAccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CarrierAccountsApi' do
    it 'should create an instance of CarrierAccountsApi' do
      expect(@instance).to be_instance_of(ShipEngineApi::CarrierAccountsApi)
    end
  end

  # unit tests for v1_connections_carriers_access_worldwide_by_carrier_id_delete
  # access_worldwide_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_access_worldwide_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_access_worldwide_post
  # access_worldwide_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_access_worldwide_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_apc_by_carrier_id_delete
  # apc_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_apc_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_apc_post
  # apc_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_apc_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_asendia_by_carrier_id_delete
  # asendia_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_asendia_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_asendia_post
  # asendia_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_asendia_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dhl_ecommerce_by_carrier_id_delete
  # dhl_ecommerce_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_dhl_ecommerce_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dhl_ecommerce_post
  # dhl_ecommerce_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_dhl_ecommerce_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dhl_express_by_carrier_id_delete
  # dhl_express_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_dhl_express_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dhl_express_post
  # dhl_express_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_dhl_express_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dhl_express_settings_by_carrier_id_get
  # dhl_express_account_carrier.get_settings
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [DhlExpressAccountSettings]
  describe 'v1_connections_carriers_dhl_express_settings_by_carrier_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dhl_express_settings_by_carrier_id_put
  # dhl_express_account_carrier.update_settings
  # 
  # @param carrier_id 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_dhl_express_settings_by_carrier_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dhl_express_uk_by_carrier_id_delete
  # dhl_express_uk_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_dhl_express_uk_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dhl_express_uk_post
  # dhl_express_uk_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_dhl_express_uk_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dpd_by_carrier_id_delete
  # dpd_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_dpd_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_dpd_post
  # dpd_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_dpd_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_endicia_by_carrier_id_delete
  # endicia_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_endicia_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_endicia_post
  # endicia_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_endicia_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_fedex_by_carrier_id_delete
  # fedex_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_fedex_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_fedex_post
  # fedex_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_fedex_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_fedex_settings_by_carrier_id_get
  # fedex_account_carrier.get_settings
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [UpsAccountSettings]
  describe 'v1_connections_carriers_fedex_settings_by_carrier_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_fedex_settings_by_carrier_id_put
  # fedex_account_carrier.update_settings
  # 
  # @param carrier_id 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_fedex_settings_by_carrier_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_fedex_uk_by_carrier_id_delete
  # fedex_uk_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_fedex_uk_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_fedex_uk_post
  # fedex_uk_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_fedex_uk_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_firstmile_by_carrier_id_delete
  # first_mile_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_firstmile_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_firstmile_post
  # first_mile_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_firstmile_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_globegistics_by_carrier_id_delete
  # globegistics_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_globegistics_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_globegistics_post
  # globegistics_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_globegistics_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_imex_by_carrier_id_delete
  # imex_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_imex_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_imex_post
  # imex_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_imex_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_newgistics_by_carrier_id_delete
  # newgistics_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_newgistics_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_newgistics_post
  # newgistics_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_newgistics_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_newgistics_settings_by_carrier_id_put
  # newgistics_account_carrier.update_settings
  # 
  # @param carrier_id 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_newgistics_settings_by_carrier_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_ontrac_by_carrier_id_delete
  # ontrac_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_ontrac_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_ontrac_post
  # ontrac_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_ontrac_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_royal_mail_by_carrier_id_delete
  # royal_mail_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_royal_mail_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_royal_mail_post
  # royal_mail_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_royal_mail_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_rr_donnelley_by_carrier_id_delete
  # rr_donnelley_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_rr_donnelley_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_rr_donnelley_post
  # rr_donnelley_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_rr_donnelley_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_stamps_com_by_carrier_id_delete
  # stamps_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_stamps_com_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_stamps_com_post
  # stamps_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_stamps_com_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_stamps_com_request_account_url_by_carrier_id_put
  # stamps_account_carrier.get_account_url
  # 
  # @param carrier_id 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [StampsAccountUrlsResponseBody]
  describe 'v1_connections_carriers_stamps_com_request_account_url_by_carrier_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_ups_by_carrier_id_delete
  # ups_account_carrier.disconnect_account
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_ups_by_carrier_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_ups_post
  # ups_account_carrier.connect_account
  # 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ConnectAccountResponseBody]
  describe 'v1_connections_carriers_ups_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_ups_settings_by_carrier_id_get
  # ups_account_carrier.get_settings
  # 
  # @param carrier_id 
  # @param [Hash] opts the optional parameters
  # @return [UpsAccountSettings]
  describe 'v1_connections_carriers_ups_settings_by_carrier_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_connections_carriers_ups_settings_by_carrier_id_put
  # ups_account_carrier.update_settings
  # 
  # @param carrier_id 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_connections_carriers_ups_settings_by_carrier_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
