=begin
#ShipEngine API

#ShipEngine™ is the world's best multi-carrier shipping API, with more than 20 supported shipping carriers.  You can easily get and compare shipping rates, print labels, track your shipments, and validate addresses anywhere in the world.  ### Worldwide Major Carrier Support Access the top global carriers in minutes—instead of weeks. Simply [connect your existing carrier accounts](https://docs.shipengine.com/docs/setup-a-carrier) in the API dashboard, and then [begin creating labels](https://docs.shipengine.com/docs/use-a-specific-service).  ### Real-Time Tracking [Track packages](https://docs.shipengine.com/docs/track-a-package) across any of our 20+ supported carrier accounts and create tracking events to keep your customers up-to-date. Easily integrate real-time tracking information for shipments into your app, email, or SMS.  ### Get Rates Across Carriers Make sure you ship as cost-effectively as possible by [quickly comparing rates](https://docs.shipengine.com/docs/get-shipping-rates) using the ShipEngine Rates API. As long as you have the carrier connected to your account, you'll be able to see and compare different rates and services.  ### Global Address Validation No matter your shipping volume, failed deliveries and address change surcharges cut into your bottom line and damage perception with customers. Our address validation services ensure your packages make it to the right place the first time. [Learn how to leverage our address validation services here.](https://docs.shipengine.com/docs/address-validation)  ShipEngine supports address validation for over 180 countries, including the United States, Canada, Great Britain, Australia, Germany, France, Norway, Spain, Sweden, Israel, Italy, and more. 

OpenAPI spec version: 1.0.0
Contact: sales@shipengine.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'date'

module ShipEngineApi
  # A label represents the physical sticker that you affix to a package to ship it.  ShipEngine makes it easy for you to [create labels](https://docs.shipengine.com/docs/quickstart-create-a-label) and then download them in PDF, PNG, or ZPL format so you can print them.
  class Label
    # A string that uniquely identifies the label. This ID is generated by ShipEngine when the label is created.
    attr_accessor :label_id

    attr_accessor :status

    # The shipment that this label is for.  ShipEngine can create a shipment for you automatically when you [create a label](https://docs.shipengine.com/docs/quickstart-create-a-label), or you can [create your own shipment](https://docs.shipengine.com/docs/create-a-shipment) and then [use it to print a label](https://docs.shipengine.com/docs/use-a-shipment-to-print-a-label)
    attr_accessor :shipment_id

    # The date that the package was (or will be) shippped.  ShipEngine will take the day of week into consideration when setting this.  For example, if a carrier does not operate on Sundays, then a package that would have shipped on Sunday will ship on Monday instead.
    attr_accessor :ship_date

    # The date and time that the label was created in ShipEngine.
    attr_accessor :created_at

    # The tracking number for the package. Tracking number formats vary across carriers.
    attr_accessor :tracking_number

    # Indicates whether this is a return label.  You may also want to set the `rma_number` so you know what is being returned.
    attr_accessor :is_return_label

    # An optional Return Merchandise Authorization number.  This field is useful for return labels.  You can set it to any string value.
    attr_accessor :rma_number

    # Indicates whether this is an international shipment.  That is, the originating country and destination country are different.
    attr_accessor :is_international

    # If this label was created as part of a [batch](https://docs.shipengine.com/docs/using-batches), then this is the unique ID of that batch.
    attr_accessor :batch_id

    # The unique ID of the [carrier account](https://docs.shipengine.com/docs/setup-a-carrier) that was used to create this label
    attr_accessor :carrier_id

    # The [carrier service](https://docs.shipengine.com/docs/use-a-specific-service) that will be used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, etc.
    attr_accessor :service_code

    # Indicates whether the label has been [voided](https://docs.shipengine.com/docs/void-a-label)
    attr_accessor :voided

    # The date and time that the label was [voided](https://docs.shipengine.com/docs/void-a-label), or `null` if the label has not been voided
    attr_accessor :voided_at

    attr_accessor :label_format

    attr_accessor :label_layout

    # Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status and each package will have a `tracking_number`.
    attr_accessor :trackable

    # The [shipping carrier](https://docs.shipengine.com/docs/setup-a-carrier) who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc.
    attr_accessor :carrier_code

    attr_accessor :tracking_status

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'label_id' => :'label_id',
        :'status' => :'status',
        :'shipment_id' => :'shipment_id',
        :'ship_date' => :'ship_date',
        :'created_at' => :'created_at',
        :'tracking_number' => :'tracking_number',
        :'is_return_label' => :'is_return_label',
        :'rma_number' => :'rma_number',
        :'is_international' => :'is_international',
        :'batch_id' => :'batch_id',
        :'carrier_id' => :'carrier_id',
        :'service_code' => :'service_code',
        :'voided' => :'voided',
        :'voided_at' => :'voided_at',
        :'label_format' => :'label_format',
        :'label_layout' => :'label_layout',
        :'trackable' => :'trackable',
        :'carrier_code' => :'carrier_code',
        :'tracking_status' => :'tracking_status'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'label_id' => :'String',
        :'status' => :'LabelStatus',
        :'shipment_id' => :'String',
        :'ship_date' => :'DateTime',
        :'created_at' => :'DateTime',
        :'tracking_number' => :'String',
        :'is_return_label' => :'BOOLEAN',
        :'rma_number' => :'String',
        :'is_international' => :'BOOLEAN',
        :'batch_id' => :'String',
        :'carrier_id' => :'String',
        :'service_code' => :'String',
        :'voided' => :'BOOLEAN',
        :'voided_at' => :'DateTime',
        :'label_format' => :'LabelFormat',
        :'label_layout' => :'LabelLayout',
        :'trackable' => :'BOOLEAN',
        :'carrier_code' => :'String',
        :'tracking_status' => :'TrackingStatus'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'label_id')
        self.label_id = attributes[:'label_id']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.has_key?(:'shipment_id')
        self.shipment_id = attributes[:'shipment_id']
      end

      if attributes.has_key?(:'ship_date')
        self.ship_date = attributes[:'ship_date']
      end

      if attributes.has_key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.has_key?(:'tracking_number')
        self.tracking_number = attributes[:'tracking_number']
      end

      if attributes.has_key?(:'is_return_label')
        self.is_return_label = attributes[:'is_return_label']
      end

      if attributes.has_key?(:'rma_number')
        self.rma_number = attributes[:'rma_number']
      end

      if attributes.has_key?(:'is_international')
        self.is_international = attributes[:'is_international']
      end

      if attributes.has_key?(:'batch_id')
        self.batch_id = attributes[:'batch_id']
      end

      if attributes.has_key?(:'carrier_id')
        self.carrier_id = attributes[:'carrier_id']
      end

      if attributes.has_key?(:'service_code')
        self.service_code = attributes[:'service_code']
      end

      if attributes.has_key?(:'voided')
        self.voided = attributes[:'voided']
      end

      if attributes.has_key?(:'voided_at')
        self.voided_at = attributes[:'voided_at']
      end

      if attributes.has_key?(:'label_format')
        self.label_format = attributes[:'label_format']
      end

      if attributes.has_key?(:'label_layout')
        self.label_layout = attributes[:'label_layout']
      end

      if attributes.has_key?(:'trackable')
        self.trackable = attributes[:'trackable']
      end

      if attributes.has_key?(:'carrier_code')
        self.carrier_code = attributes[:'carrier_code']
      end

      if attributes.has_key?(:'tracking_status')
        self.tracking_status = attributes[:'tracking_status']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @label_id.nil?
        invalid_properties.push('invalid value for "label_id", label_id cannot be nil.')
      end

      if @label_id.to_s.length > 25
        invalid_properties.push('invalid value for "label_id", the character length must be smaller than or equal to 25.')
      end

      if @label_id.to_s.length < 1
        invalid_properties.push('invalid value for "label_id", the character length must be great than or equal to 1.')
      end

      if @label_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
        invalid_properties.push('invalid value for "label_id", must conform to the pattern /^se(-[a-z0-9]+)+$/.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @shipment_id.nil?
        invalid_properties.push('invalid value for "shipment_id", shipment_id cannot be nil.')
      end

      if @shipment_id.to_s.length > 25
        invalid_properties.push('invalid value for "shipment_id", the character length must be smaller than or equal to 25.')
      end

      if @shipment_id.to_s.length < 1
        invalid_properties.push('invalid value for "shipment_id", the character length must be great than or equal to 1.')
      end

      if @shipment_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
        invalid_properties.push('invalid value for "shipment_id", must conform to the pattern /^se(-[a-z0-9]+)+$/.')
      end

      if @ship_date.nil?
        invalid_properties.push('invalid value for "ship_date", ship_date cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @tracking_number.nil?
        invalid_properties.push('invalid value for "tracking_number", tracking_number cannot be nil.')
      end

      if @tracking_number.to_s.length < 1
        invalid_properties.push('invalid value for "tracking_number", the character length must be great than or equal to 1.')
      end

      if @is_return_label.nil?
        invalid_properties.push('invalid value for "is_return_label", is_return_label cannot be nil.')
      end

      if @rma_number.nil?
        invalid_properties.push('invalid value for "rma_number", rma_number cannot be nil.')
      end

      if @is_international.nil?
        invalid_properties.push('invalid value for "is_international", is_international cannot be nil.')
      end

      if @batch_id.nil?
        invalid_properties.push('invalid value for "batch_id", batch_id cannot be nil.')
      end

      if @batch_id.to_s.length > 25
        invalid_properties.push('invalid value for "batch_id", the character length must be smaller than or equal to 25.')
      end

      if @batch_id.to_s.length < 1
        invalid_properties.push('invalid value for "batch_id", the character length must be great than or equal to 1.')
      end

      if @batch_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
        invalid_properties.push('invalid value for "batch_id", must conform to the pattern /^se(-[a-z0-9]+)+$/.')
      end

      if @carrier_id.nil?
        invalid_properties.push('invalid value for "carrier_id", carrier_id cannot be nil.')
      end

      if @carrier_id.to_s.length > 25
        invalid_properties.push('invalid value for "carrier_id", the character length must be smaller than or equal to 25.')
      end

      if @carrier_id.to_s.length < 1
        invalid_properties.push('invalid value for "carrier_id", the character length must be great than or equal to 1.')
      end

      if @carrier_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
        invalid_properties.push('invalid value for "carrier_id", must conform to the pattern /^se(-[a-z0-9]+)+$/.')
      end

      if @service_code.nil?
        invalid_properties.push('invalid value for "service_code", service_code cannot be nil.')
      end

      if @service_code !~ Regexp.new(/^[a-z0-9]+(_[a-z0-9-]+)* ?$/)
        invalid_properties.push('invalid value for "service_code", must conform to the pattern /^[a-z0-9]+(_[a-z0-9-]+)* ?$/.')
      end

      if @voided.nil?
        invalid_properties.push('invalid value for "voided", voided cannot be nil.')
      end

      if @voided_at.nil?
        invalid_properties.push('invalid value for "voided_at", voided_at cannot be nil.')
      end

      if @label_format.nil?
        invalid_properties.push('invalid value for "label_format", label_format cannot be nil.')
      end

      if @label_layout.nil?
        invalid_properties.push('invalid value for "label_layout", label_layout cannot be nil.')
      end

      if @trackable.nil?
        invalid_properties.push('invalid value for "trackable", trackable cannot be nil.')
      end

      if @carrier_code.nil?
        invalid_properties.push('invalid value for "carrier_code", carrier_code cannot be nil.')
      end

      if @carrier_code !~ Regexp.new(/^[a-z0-9]+(_[a-z0-9]+)*$/)
        invalid_properties.push('invalid value for "carrier_code", must conform to the pattern /^[a-z0-9]+(_[a-z0-9]+)*$/.')
      end

      if @tracking_status.nil?
        invalid_properties.push('invalid value for "tracking_status", tracking_status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @label_id.nil?
      return false if @label_id.to_s.length > 25
      return false if @label_id.to_s.length < 1
      return false if @label_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
      return false if @status.nil?
      return false if @shipment_id.nil?
      return false if @shipment_id.to_s.length > 25
      return false if @shipment_id.to_s.length < 1
      return false if @shipment_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
      return false if @ship_date.nil?
      return false if @created_at.nil?
      return false if @tracking_number.nil?
      return false if @tracking_number.to_s.length < 1
      return false if @is_return_label.nil?
      return false if @rma_number.nil?
      return false if @is_international.nil?
      return false if @batch_id.nil?
      return false if @batch_id.to_s.length > 25
      return false if @batch_id.to_s.length < 1
      return false if @batch_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
      return false if @carrier_id.nil?
      return false if @carrier_id.to_s.length > 25
      return false if @carrier_id.to_s.length < 1
      return false if @carrier_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
      return false if @service_code.nil?
      return false if @service_code !~ Regexp.new(/^[a-z0-9]+(_[a-z0-9-]+)* ?$/)
      return false if @voided.nil?
      return false if @voided_at.nil?
      return false if @label_format.nil?
      return false if @label_layout.nil?
      return false if @trackable.nil?
      return false if @carrier_code.nil?
      return false if @carrier_code !~ Regexp.new(/^[a-z0-9]+(_[a-z0-9]+)*$/)
      return false if @tracking_status.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] label_id Value to be assigned
    def label_id=(label_id)
      if label_id.nil?
        fail ArgumentError, 'label_id cannot be nil'
      end

      if label_id.to_s.length > 25
        fail ArgumentError, 'invalid value for "label_id", the character length must be smaller than or equal to 25.'
      end

      if label_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "label_id", the character length must be great than or equal to 1.'
      end

      if label_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
        fail ArgumentError, 'invalid value for "label_id", must conform to the pattern /^se(-[a-z0-9]+)+$/.'
      end

      @label_id = label_id
    end

    # Custom attribute writer method with validation
    # @param [Object] shipment_id Value to be assigned
    def shipment_id=(shipment_id)
      if shipment_id.nil?
        fail ArgumentError, 'shipment_id cannot be nil'
      end

      if shipment_id.to_s.length > 25
        fail ArgumentError, 'invalid value for "shipment_id", the character length must be smaller than or equal to 25.'
      end

      if shipment_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "shipment_id", the character length must be great than or equal to 1.'
      end

      if shipment_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
        fail ArgumentError, 'invalid value for "shipment_id", must conform to the pattern /^se(-[a-z0-9]+)+$/.'
      end

      @shipment_id = shipment_id
    end

    # Custom attribute writer method with validation
    # @param [Object] tracking_number Value to be assigned
    def tracking_number=(tracking_number)
      if tracking_number.nil?
        fail ArgumentError, 'tracking_number cannot be nil'
      end

      if tracking_number.to_s.length < 1
        fail ArgumentError, 'invalid value for "tracking_number", the character length must be great than or equal to 1.'
      end

      @tracking_number = tracking_number
    end

    # Custom attribute writer method with validation
    # @param [Object] batch_id Value to be assigned
    def batch_id=(batch_id)
      if batch_id.nil?
        fail ArgumentError, 'batch_id cannot be nil'
      end

      if batch_id.to_s.length > 25
        fail ArgumentError, 'invalid value for "batch_id", the character length must be smaller than or equal to 25.'
      end

      if batch_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "batch_id", the character length must be great than or equal to 1.'
      end

      if batch_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
        fail ArgumentError, 'invalid value for "batch_id", must conform to the pattern /^se(-[a-z0-9]+)+$/.'
      end

      @batch_id = batch_id
    end

    # Custom attribute writer method with validation
    # @param [Object] carrier_id Value to be assigned
    def carrier_id=(carrier_id)
      if carrier_id.nil?
        fail ArgumentError, 'carrier_id cannot be nil'
      end

      if carrier_id.to_s.length > 25
        fail ArgumentError, 'invalid value for "carrier_id", the character length must be smaller than or equal to 25.'
      end

      if carrier_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "carrier_id", the character length must be great than or equal to 1.'
      end

      if carrier_id !~ Regexp.new(/^se(-[a-z0-9]+)+$/)
        fail ArgumentError, 'invalid value for "carrier_id", must conform to the pattern /^se(-[a-z0-9]+)+$/.'
      end

      @carrier_id = carrier_id
    end

    # Custom attribute writer method with validation
    # @param [Object] service_code Value to be assigned
    def service_code=(service_code)
      if service_code.nil?
        fail ArgumentError, 'service_code cannot be nil'
      end

      if service_code !~ Regexp.new(/^[a-z0-9]+(_[a-z0-9-]+)* ?$/)
        fail ArgumentError, 'invalid value for "service_code", must conform to the pattern /^[a-z0-9]+(_[a-z0-9-]+)* ?$/.'
      end

      @service_code = service_code
    end

    # Custom attribute writer method with validation
    # @param [Object] carrier_code Value to be assigned
    def carrier_code=(carrier_code)
      if carrier_code.nil?
        fail ArgumentError, 'carrier_code cannot be nil'
      end

      if carrier_code !~ Regexp.new(/^[a-z0-9]+(_[a-z0-9]+)*$/)
        fail ArgumentError, 'invalid value for "carrier_code", must conform to the pattern /^[a-z0-9]+(_[a-z0-9]+)*$/.'
      end

      @carrier_code = carrier_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          label_id == o.label_id &&
          status == o.status &&
          shipment_id == o.shipment_id &&
          ship_date == o.ship_date &&
          created_at == o.created_at &&
          tracking_number == o.tracking_number &&
          is_return_label == o.is_return_label &&
          rma_number == o.rma_number &&
          is_international == o.is_international &&
          batch_id == o.batch_id &&
          carrier_id == o.carrier_id &&
          service_code == o.service_code &&
          voided == o.voided &&
          voided_at == o.voided_at &&
          label_format == o.label_format &&
          label_layout == o.label_layout &&
          trackable == o.trackable &&
          carrier_code == o.carrier_code &&
          tracking_status == o.tracking_status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [label_id, status, shipment_id, ship_date, created_at, tracking_number, is_return_label, rma_number, is_international, batch_id, carrier_id, service_code, voided, voided_at, label_format, label_layout, trackable, carrier_code, tracking_status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = ShipEngineApi.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
