=begin
#ShipEngine API

#ShipEngine™ is the world's best multi-carrier shipping API, with more than 20 supported shipping carriers.  You can easily get and compare shipping rates, print labels, track your shipments, and validate addresses anywhere in the world.  ### Worldwide Major Carrier Support Access the top global carriers in minutes—instead of weeks. Simply [connect your existing carrier accounts](https://docs.shipengine.com/docs/setup-a-carrier) in the API dashboard, and then [begin creating labels](https://docs.shipengine.com/docs/use-a-specific-service).  ### Real-Time Tracking [Track packages](https://docs.shipengine.com/docs/track-a-package) across any of our 20+ supported carrier accounts and create tracking events to keep your customers up-to-date. Easily integrate real-time tracking information for shipments into your app, email, or SMS.  ### Get Rates Across Carriers Make sure you ship as cost-effectively as possible by [quickly comparing rates](https://docs.shipengine.com/docs/get-shipping-rates) using the ShipEngine Rates API. As long as you have the carrier connected to your account, you'll be able to see and compare different rates and services.  ### Global Address Validation No matter your shipping volume, failed deliveries and address change surcharges cut into your bottom line and damage perception with customers. Our address validation services ensure your packages make it to the right place the first time. [Learn how to leverage our address validation services here.](https://docs.shipengine.com/docs/address-validation)  ShipEngine supports address validation for over 180 countries, including the United States, Canada, Great Britain, Australia, Germany, France, Norway, Spain, Sweden, Israel, Italy, and more. 

OpenAPI spec version: 1.0.0
Contact: sales@shipengine.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'date'

module ShipEngineApi
  class SmartPostHub
    
    NONE = 'none'.freeze
    ALLENTOWN_PA = 'allentown_pa'.freeze
    ATLANTA_GA = 'atlanta_ga'.freeze
    BALTIMORE_MD = 'baltimore_md'.freeze
    CHARLOTTE_NC = 'charlotte_nc'.freeze
    CHINO_CA = 'chino_ca'.freeze
    DALLAS_TX = 'dallas_tx'.freeze
    DENVER_CO = 'denver_co'.freeze
    DETROIT_MI = 'detroit_mi'.freeze
    EDISON_NJ = 'edison_nj'.freeze
    GROVE_CITY_OH = 'grove_city_oh'.freeze
    GROVEPORT_OH = 'groveport_oh'.freeze
    HOUSTON_TX = 'houston_tx'.freeze
    INDIANAPOLIS_IN = 'indianapolis_in'.freeze
    KANSAS_CITY_KS = 'kansas_city_ks'.freeze
    LOS_ANGELES_CA = 'los_angeles_ca'.freeze
    MARTINSBURG_WV = 'martinsburg_wv'.freeze
    MEMPHIS_TN = 'memphis_tn'.freeze
    MINNEAPOLIS_MN = 'minneapolis_mn'.freeze
    NEW_BERLIN_WI = 'new_berlin_wi'.freeze
    NORTHBOROUGH_MA = 'northborough_ma'.freeze
    ORLANDO_FL = 'orlando_fl'.freeze
    PHONEIX_AZ = 'phoneix_az'.freeze
    PITTSBURGH_PA = 'pittsburgh_pa'.freeze
    RENO_NV = 'reno_nv'.freeze
    SACRAMENTO_CA = 'sacramento_ca'.freeze
    SALT_LAKE_CITY_UT = 'salt_lake_city_ut'.freeze
    SEATTLE_WA = 'seattle_wa'.freeze
    ST_LOUIS_MO = 'st_louis_mo'.freeze
    WINDSOR_CT = 'windsor_ct'.freeze
    NEWARK_NY = 'newark_ny'.freeze
    SOUTH_BRUNSWICK_NJ = 'south_brunswick_nj'.freeze
    SCRANTON_PA = 'scranton_pa'.freeze
    WHEELING_IL = 'wheeling_il'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = SmartPostHub.constants.select { |c| SmartPostHub::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #SmartPostHub" if constantValues.empty?
      value
    end
  end
end
